import ply.lex as lex
import ply.yacc as yacc


# 6502 instructions
opcodes = {'ADC': {'IMMEDIATE': 0x69,
                   'ZERO': 0x65,
                   'ABSOLUTE': 0x6D,
                   'OFFSET': {'X': {'ZERO': 0x75,
                                    'ABSOLUTE': 0x7D},
                              'Y': {'ABSOLUTE': 0x79}},
                   'INDIRECT':{'X': 0x61,
                               'Y': 0x71}},
           'AND': {'IMMEDIATE': 0x29,
                   'ZERO': 0x25,
                   'ABSOLUTE': 0x2D,
                   'OFFSET': {'X': {'ZERO': 0x35,
                                    'ABSOLUTE': 0x3D},
                              'Y': {'ABSOLUTE': 0x39}},
                   'INDIRECT': {'X': 0x21,
                                'Y': 0x31}},
           'ASL': {'REGISTER': {'A': 0x0A},
                   'ZERO': 0x06,
                   'ABSOLUTE': 0x0E,
                   'OFFSET': {'X': {'ZERO': 0x16,
                                    'ABSOLUTE': 0x1E}}},
           'BIT': {'ZERO': 0x24,
                   'ABSOLUTE': 0x2C},
           'BPL': {'ZERO': 0x10},
           'BMI': {'ZERO': 0x30},
           'BVC': {'ZERO': 0x50},
           'BVS': {'ZERO': 0x70},
           'BCC': {'ZERO': 0x90},
           'BCS': {'ZERO': 0xB0},
           'BNE': {'ZERO': 0xD0},
           'BEQ': {'ZERO': 0xF0},
           'BRK': {'IMPLIED': 0x00},
           'CMP': {'IMMEDIATE': 0xC9,
                   'ZERO': 0xC5,
                   'OFFSET': {'X': {'ZERO': 0xD5,
                                    'ABSOLUTE': 0xDD},
                              'Y': {'ABSOLUTE': 0xD9}},
                   'ABSOLUTE': 0xCD,
                   'INDIRECT': {'X': 0xC1,
                                'Y': 0xD1}},
           'CPX': {'IMMEDIATE': 0xE0,
                   'ZERO': 0xE4,
                   'ABSOLUTE': 0xEC},
           'CPY': {'IMMEDIATE': 0xC0,
                   'ZERO': 0xC4,
                   'ABSOLUTE': 0xCC},
           'DEC': {'ZERO': 0xC6,
                   'ABSOLUTE': 0xCE,
                   'OFFSET': {'X': {'ZERO': 0xD6,
                                    'ABSOLUTE': 0xDE}}},
           'EOR': {'IMMEDIATE': 0x49,
                   'ZERO': 0x45,
                   'OFFSET': {'X': {'ZERO': 0x55,
                                    'ABSOLUTE': 0x5D},
                              'Y': {'ABSOLUTE': 0x59}},
                   'ABSOLUTE': 0x4D,
                   'INDIRECT': {'X': 0x41,
                                'Y': 0x51}},
           'CLC': {'IMPLIED': 0x18},
           'SEC': {'IMPLIED': 0x38},
           'CLI': {'IMPLIED': 0x58},
           'SEI': {'IMPLIED': 0x78},
           'CLV': {'IMPLIED': 0xB8},
           'CLD': {'IMPLIED': 0xD8},
           'SED': {'IMPLIED': 0xF8},
           'INC': {'ZERO': 0xE6,
                   'ABSOLUTE': 0xEE,
                   'OFFSET': {'X': {'ZERO': 0xF6,
                                    'ABSOLUTE': 0xFE}}},
           'JMP': {'ABSOLUTE': 0x4C,
                   'INDIRECT': 0x6C},
           'JSR': {'ABSOLUTE': 0x20},
           'LDA': {'IMMEDIATE': 0xA9,
                   'ZERO': 0xA5,
                   'OFFSET': {'X': {'ZERO': 0xB5,
                                    'ABSOLUTE': 0xBD},
                              'Y': {'ABSOLUTE': 0xB9}},
                   'ABSOLUTE': 0xAD,
                   'INDIRECT': {'X': 0xA1,
                                'Y': 0xB1}},
           'LDX': {'IMMEDIATE': 0xA2,
                   'ZERO': 0xA6,
                   'OFFSET': {'Y': {'ZERO': 0xB6,
                                    'ABSOLUTE': 0xBE}},
                   'ABSOLUTE': 0xAE},
           'LDY': {'IMMEDIATE': 0xA0,
                   'ZERO': 0xA4,
                   'OFFSET': {'X': {'ZERO': 0xB4,
                                    'ABSOLUTE': 0xBC}},
                   'ABSOLUTE': 0xAC},
           'LSR': {'REGISTER': {'A': 0x4A},
                   'ZERO': 0x46,
                   'ABSOLUTE': 0x4E,
                   'OFFSET': {'X': {'ZERO': 0x56,
                                    'ABSOLUTE': 0x5E}}},
           'NOP': {'IMPLIED': 0xEA},
           'ORA': {'IMMEDIATE': 0x09,
                   'ZERO': 0x05,
                   'ABSOLUTE': 0x0D,
                   'INDIRECT': {'X': 0x01,
                                'Y': 0x11},
                   'OFFSET': {'X': {'ZERO': 0x15,
                                    'ABSOLUTE': 0x1D},
                              'Y': {'ABSOLUTE': 0x19}}},
           'TAX': {'IMPLIED': 0xAA},
           'TXA': {'IMPLIED': 0x8A},
           'DEX': {'IMPLIED': 0xCA},
           'INX': {'IMPLIED': 0xE8},
           'TAY': {'IMPLIED': 0xA8},
           'TYA': {'IMPLIED': 0x98},
           'DEY': {'IMPLIED': 0x88},
           'INY': {'IMPLIED': 0xC8},
           'ROL': {'REGISTER': {'A': 0x2A},
                   'ZERO': 0x26,
                   'ABSOLUTE': 0x2E,
                   'OFFSET': {'X': {'ZERO': 0x26,
                                    'ABSOLUTE': 0x3E}}},
           'ROR': {'REGISTER': {'A': 0x6A},
                   'ZERO': 0x66,
                   'ABSOLUTE': 0x6E,
                   'OFFSET': {'X': {'ZERO': 0x76,
                                    'ABSOLUTE': 0x7E}}},
           'RTI': {'IMPLIED': 0x40},
           'RTS': {'IMPLIED': 0x60},
           'SBC': {'IMMEDIATE': 0xE9,
                   'ZERO': 0xE5,
                   'ABSOLUTE': 0xED,
                   'OFFSET': {'X': {'ZERO': 0xF5,
                                    'ABSOLUTE': 0xFD},
                              'Y': {'ABSOLUTE': 0xF9}},
                   'INDIRECT': {'X': 0xE1,
                                'Y': 0xF1}},
           'STA': {'ZERO': 0x85,
                   'ABSOLUTE': 0x8D,
                   'OFFSET': {'X': {'ZERO': 0x95,
                                    'ABSOLUTE': 0x9D},
                              'Y': {'ABSOLUTE': 0x99}},
                   'INDIRECT': {'X': 0x81,
                                'Y': 0x91}},
            'TXS': {'IMPLIED': 0x9A},
            'TSX': {'IMPLIED': 0xBA},
            'PHA': {'IMPLIED': 0x48},
            'PLA': {'IMPLIED': 0x68},
            'PHP': {'IMPLIED': 0x08},
            'PLP': {'IMPLIED': 0x28},
            'STX': {'ZERO': 0x86,
                    'ABSOLUTE': 0x8E,
                    'OFFSET': {'Y': {'ZERO': 0x8E}}},
            'STY': {'ZERO': 0x84,
                    'ABSOLUTE': 0x8C,
                    'OFFSET': {'X': {'ZERO': 0x94}}}}
instruction_set = opcodes.keys()
directives = ['ORG', 'TARGET', 'INCLUDE']
tokens = ['IDENTIFIER', 'STRING', 'NUMBER', 'HEX', 'INSTRUCTION', 'DIRECTIVE',
          'REGISTER', 'BINARY']
